name: CI/CD

on:
  push:
    branches:
      - main
      - release
    tags:
      - '*'

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3072m -XX:MaxMetaspaceSize=1g -Xms512m -XX:+HeapDumpOnOutOfMemoryError"
  SIGNING_KEYSTORE_GITHUB: ${{ secrets.SIGNING_KEYSTORE_GITHUB }}
  SIGNING_PROPERTIES_GITHUB: ${{ secrets.SIGNING_PROPERTIES_GITHUB }}
  GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
  VOICE_USE_PROPRIETARY_LIBRARIES: "false"

jobs:
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3b9b8c884f6b4bb4d5be2779c26374abadae0871

      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Setup Signing
        run: ./ci_signing_setup.sh

      - name: Build Github Libre APK
        run: ./gradlew :app:assembleGithubLibreRelease

      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            app/build/outputs/apk/githubProprietary/release/app-github-proprietary-release.apk
            app/build/outputs/apk/githubLibre/release/app-github-libre-release.apk
